[package]
name = "chorus-macros"
version = "0.6.0"
edition = "2021"
license = "MPL-2.0"
description = "Macros for the chorus crate."
repository = "https://github.com/polyphony-chat/chorus"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.29"
async-trait = "0.1.73"
